### ISSUE TITLE
Wallpaper.systemScreen() not Working

### ISSUE THREAD

**Issue by Not-Dhanraj** [pratiktimer/setWallpaperplugin#22]
Exception has occurred.
PlatformException (PlatformException(error, Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
	at android.content.ContextWrapper.getPackageManager(ContextWrapper.java:91)
	at android.app.Activity.requestPermissions(Activity.java:4178)
	at com.prateektimer.wallpaper.WallpaperPlugin.setSystemWallpaper(WallpaperPlugin.java:109)
	at com.prateektimer.wallpaper.WallpaperPlugin.onMethodCall(WallpaperPlugin.java:92)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
))

**Comment by pratiktimer** [comment]
can you pleae check with latest version 1.1.0 . if you are still having this issue

**Comment by Not-Dhanraj** [comment]
Sure, let me check
